packages:
  - .

allowBuilds:
  '@tailwindcss/oxide': set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - protobufjs
  - sharp
  - unrs-resolver
