import { AltmanZResult, FundamentalCompositeScores, FundamentalRatios, FundamentalRecommendation, FundamentalVerdict, PiotroskiResult } from './types';

const DISCLAIMER = 'Educational analysis only, derived from the fundamental data currently available for this symbol. Not financial advice, not a guarantee of future returns, and not a substitute for your own research or a SEBI/SEC-registered advisor.';

function verdictFromScore(score: number): FundamentalVerdict {
  if (score >= 80) return 'Strong Buy';
  if (score >= 65) return 'Buy';
  if (score >= 55) return 'Accumulate';
  if (score >= 40) return 'Hold';
  if (score >= 25) return 'Reduce';
  if (score >= 10) return 'Sell';
  return 'Strong Sell';
}

/**
 * Combines the fundamental composite scores (and optionally a technical trend score from
 * lib/aiPrediction.ts, -100..100) into a single tiered verdict with plain-English
 * reasoning. Every reasoning line references a number that was actually computed - nothing
 * here is generated by an LLM, so there is nothing to hallucinate.
 */
export function generateFundamentalRecommendation(
  scores: FundamentalCompositeScores,
  ratios: FundamentalRatios,
  piotroski: PiotroskiResult,
  altmanZ: AltmanZResult,
  technicalTrendScore?: number,
): FundamentalRecommendation {
  const reasoning: string[] = [];
  const cautionNotes: string[] = [];

  let blendedScore = scores.overallScore;
  if (typeof technicalTrendScore === 'number') {
    // Fundamentals lead (70%), technical trend is a confirming/timing signal (30%).
    const technicalAs100 = (technicalTrendScore + 100) / 2;
    blendedScore = scores.overallScore * 0.7 + technicalAs100 * 0.3;
    reasoning.push(`Blended score combines fundamentals (${scores.overallScore}/100, 70% weight) with the current technical trend (${technicalAs100.toFixed(0)}/100, 30% weight).`);
  }

  if (scores.qualityScore >= 65) {
    reasoning.push(`Quality score is ${scores.qualityScore}/100 - returns on equity/capital and margins are solid.`);
  } else if (scores.qualityScore <= 35) {
    cautionNotes.push(`Quality score is only ${scores.qualityScore}/100 - profitability/capital efficiency is weak relative to the bands used here.`);
  }

  if (scores.valueScore >= 65) {
    reasoning.push(`Value score is ${scores.valueScore}/100 - valuation multiples look reasonable to cheap versus the fixed bands used here.`);
  } else if (scores.valueScore <= 35) {
    cautionNotes.push(`Value score is only ${scores.valueScore}/100 - the stock is priced at a premium on the multiples available (PE ${ratios.peRatio?.toFixed(1) ?? 'n/a'}, PB ${ratios.pbRatio?.toFixed(1) ?? 'n/a'}).`);
  }

  if (scores.growthScore >= 65) {
    reasoning.push(`Growth score is ${scores.growthScore}/100 - revenue and/or profit growth (${ratios.revenueGrowthPct?.toFixed(1) ?? 'n/a'}% revenue YoY) is strong.`);
  } else if (scores.growthScore <= 35) {
    cautionNotes.push(`Growth score is only ${scores.growthScore}/100 - revenue/profit growth is soft or contracting.`);
  }

  if (scores.financialHealthScore >= 65) {
    reasoning.push(`Financial health score is ${scores.financialHealthScore}/100 - liquidity and leverage look manageable.`);
  } else if (scores.financialHealthScore <= 35) {
    cautionNotes.push(`Financial health score is only ${scores.financialHealthScore}/100 - leverage and/or liquidity look stretched (debt/equity ${ratios.debtToEquity?.toFixed(2) ?? 'n/a'}, current ratio ${ratios.currentRatio?.toFixed(2) ?? 'n/a'}).`);
  }

  const evaluatedPiotroski = piotroski.breakdown.filter(b => b.passed !== null).length;
  if (evaluatedPiotroski > 0) {
    reasoning.push(`Piotroski F-Score: ${piotroski.score}/9 (${evaluatedPiotroski} of 9 criteria could be evaluated from available data).`);
    if (piotroski.score <= 3 && evaluatedPiotroski >= 6) {
      cautionNotes.push('Piotroski F-Score is low - several fundamental trend checks (profitability, leverage, efficiency) failed year-over-year.');
    }
  }

  if (altmanZ.zone === 'Distress') {
    cautionNotes.push(`Altman Z-Score (${altmanZ.score}) is in the 'distress' zone - elevated bankruptcy/solvency risk by this model.`);
  } else if (altmanZ.zone === 'Safe' && typeof altmanZ.score === 'number') {
    reasoning.push(`Altman Z-Score (${altmanZ.score}) is in the 'safe' zone for solvency risk.`);
  }

  if (scores.dataCompleteness < 50) {
    cautionNotes.push(`Only ${scores.dataCompleteness}% of the inputs behind this score were available from the current data source - treat this verdict as a partial read, not a complete one.`);
  }

  const verdict = verdictFromScore(blendedScore);
  // Confidence reflects both how far the blended score sits from the "Hold" midpoint and
  // how much of the underlying data was actually available - a confident-looking verdict
  // built on 20% data coverage is not something this should ever imply.
  const distanceFromMid = Math.abs(blendedScore - 50) / 50; // 0..1
  const confidence = Math.round(Math.max(15, Math.min(90, distanceFromMid * 70 + scores.dataCompleteness * 0.3)));

  if (reasoning.length === 0) {
    reasoning.push('Composite scores sit close to neutral across quality, value, growth, and financial health.');
  }

  return {
    verdict,
    confidence,
    reasoning,
    cautionNotes,
    disclaimer: DISCLAIMER,
  };
}
